begin;
select plan(20);
select has_table('private','subscriptions','all subscriptions are projected privately');
select has_table('private','invoices','invoices are projected privately');
select has_table('private','stripe_webhook_events','minimal webhook ledger exists');
select ok(public.claim_stripe_event('evt_claim','invoice.updated',now()),'first webhook delivery is claimed');
select is(public.claim_stripe_event('evt_claim','invoice.updated',now()),false,'duplicate processing delivery is deduplicated');
select public.finish_stripe_event('evt_claim','temporary_failure');
select ok(public.claim_stripe_event('evt_claim','invoice.updated',now()),'failed event is retryable');

insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,raw_user_meta_data,raw_app_meta_data,created_at,updated_at)
values('66666666-6666-4666-8666-666666666666','00000000-0000-0000-0000-000000000000','authenticated','authenticated','billing@example.test','',now(),'{}','{}',now(),now());
insert into private.stripe_customers(user_id,stripe_customer_id) values('66666666-6666-4666-8666-666666666666','cus_billing');

select lives_ok($$select public.apply_billing_snapshot('evt_initial','cus_billing',jsonb_build_object('id','sub_main','status','incomplete','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 day'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now())),jsonb_build_object('id','in_initial','billingReason','subscription_create','status','open','paid',false,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',6900,'amountPaid',0,'amountRefunded',0,'paymentIntentId','pi_initial','hasOpenDispute',false))$$,'initial failure reconciles without granting');
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['free_read_only'::text],'initial failure never grants Pro');
select is((select grace_ends_at from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'),null,'initial failure has no grace');

select public.apply_billing_snapshot('evt_paid','cus_billing',jsonb_build_object('id','sub_main','status','active','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()-interval '1 year'),'currentPeriodEnd',extract(epoch from now()+interval '1 day'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '1 second')),jsonb_build_object('id','in_paid','billingReason','subscription_create','status','paid','paid',true,'periodStart',extract(epoch from now()-interval '1 year'),'periodEnd',extract(epoch from now()-interval '1 day'),'amountDue',6900,'amountPaid',6900,'amountRefunded',0,'paymentIntentId','pi_paid','hasOpenDispute',false));
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['pro_active'::text],'invoice.paid activates Pro');

select public.apply_billing_snapshot('evt_renewal_failed','cus_billing',jsonb_build_object('id','sub_main','status','past_due','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '2 seconds')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','open','paid',false,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',0,'amountRefunded',0,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['pro_grace'::text],'qualifying renewal failure grants grace');
select is((select grace_ends_at-first_recovery_required_at from private.invoices where stripe_invoice_id='in_renewal'),interval '7 days','grace deadline is exactly seven days');

create temporary table saved_deadline as select grace_ends_at from private.invoices where stripe_invoice_id='in_renewal';
select public.apply_billing_snapshot('evt_terminal','cus_billing',jsonb_build_object('id','sub_main','status','unpaid','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '3 seconds')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','open','paid',false,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',0,'amountRefunded',0,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select is((select grace_ends_at from private.invoices where stripe_invoice_id='in_renewal'),(select grace_ends_at from saved_deadline),'terminal subscription state cannot shorten grace');

select public.apply_billing_snapshot('evt_recovered','cus_billing',jsonb_build_object('id','sub_main','status','active','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '4 seconds')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','paid','paid',true,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',9600,'amountRefunded',0,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['pro_active'::text],'paid renewal recovers active entitlement');
select is((select grace_ends_at from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'),null,'paid recovery clears grace');

select public.apply_billing_snapshot('evt_partial','cus_billing',jsonb_build_object('id','sub_main','status','active','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '5 seconds')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','paid','paid',true,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',9600,'amountRefunded',1000,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['pro_active'::text],'partial refund does not suspend');
select public.apply_billing_snapshot('evt_refund','cus_billing',jsonb_build_object('id','sub_main','status','active','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '6 seconds')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','paid','paid',true,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',9600,'amountRefunded',9600,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select results_eq($$select entitlement from public.account_entitlements where user_id='66666666-6666-4666-8666-666666666666'$$,array['pro_suspended'::text],'full current-period refund suspends');

select public.apply_billing_snapshot('evt_duplicate','cus_billing',jsonb_build_object('id','sub_duplicate','status','active','priceId','price_monthly','interval','month','created',extract(epoch from now()),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 month'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()+interval '7 seconds')),jsonb_build_object('id','in_duplicate','billingReason','subscription_create','status','paid','paid',true,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 month'),'amountDue',800,'amountPaid',800,'amountRefunded',0,'paymentIntentId','pi_duplicate','hasOpenDispute',false));
select results_eq($$select count(*)::integer from private.subscriptions where user_id='66666666-6666-4666-8666-666666666666' and is_canonical$$,array[1],'canonical selection is deterministic');
select results_eq($$select count(*)::integer from private.subscriptions where user_id='66666666-6666-4666-8666-666666666666' and duplicate_remediation_status='pending'$$,array[1],'later payable duplicate is marked once for remediation');

select public.apply_billing_snapshot('evt_old','cus_billing',jsonb_build_object('id','sub_main','status','canceled','priceId','price_annual','interval','year','created',extract(epoch from now()-interval '1 year'),'currentPeriodStart',extract(epoch from now()),'currentPeriodEnd',extract(epoch from now()+interval '1 year'),'cancelAtPeriodEnd',false,'updated',extract(epoch from now()-interval '1 day')),jsonb_build_object('id','in_renewal','billingReason','subscription_cycle','status','paid','paid',true,'periodStart',extract(epoch from now()),'periodEnd',extract(epoch from now()+interval '1 year'),'amountDue',9600,'amountPaid',9600,'amountRefunded',0,'paymentIntentId','pi_renewal','hasOpenDispute',false));
select results_eq($$select status from private.subscriptions where stripe_subscription_id='sub_main'$$,array['active'::text],'older subscription snapshot cannot regress current state');

select * from finish();
rollback;
